name: MiniPlaceholders-Chunky-Expansion
version: '${version}'
author: 4drian3d
main: io.github.miniplaceholders.expansion.chunky.paper.PaperPlugin
api-version: '1.20'
folia-supported: true
dependencies:
  server:
    MiniPlaceholders:
      required: true
      load: BEFORE
    Chunky:
      required: true
      load: BEFORE
