name: MiniPlaceholdersExample-Expansion
version: '${version}'
author: 4drian3d
main: io.github.miniplaceholders.expansion.example.paper.PaperPlugin
api-version: '1.19'
folia-supported: true
dependencies:
  server:
    MiniPlaceholders:
      required: true
  # Add some plugin dependency
  # spark:
  #   required: true